### ISSUE TITLE
[refactor] 게시글 외래키 제거

### ISSUE THREAD

**Issue by kmi0817** [boostcampwm2023/iOS07-traveline#149]
## 📌  Issue

각 태그에 해당하는 컬럼에 문자열 그대로 박아 넣겠습니다...ㅜ

## ✅  To-do

- [ ] 태그 테이블 관련 파일 제거
- [ ] Posting 엔티티 수정
- [ ] Posting 모듈 수정

**Comment by kmi0817** [comment]
보류하겠습니다...
