### ISSUE TITLE
[chore] 리뷰 반영 및 Swagger 문서 정리

### ISSUE THREAD

**Issue by kmi0817** [boostcampwm2023/iOS07-traveline#202]
## 📌  Issue

부수적인 작업,,, 메인 작업하다가 리프레시가 필요할 때 할 만한 녀석들

## ✅  To-do

- [x] 카카오 지도 API 요청 시 axios 대신 HttpModule 사용
- [x] Swagger: `GET` /postings의 offset, limit 수정
- [x] Swagger: `POST` /postings/{id}/like 반환 예제 수정
- [x] Swagger: 누락된 에러 추가
- [ ] ~~Swagger: 반환되는 필드의 nullable 여부 표시 (가능한가??)~~ => 방법을 찾지 못 했음다
