### ISSUE TITLE
[fix] 클라이언트 피드백 반영

### ISSUE THREAD

**Issue by kmi0817** [boostcampwm2023/iOS07-traveline#223]
## 📌  Issue

클라이언트 분들이 서버 API를 붙이다가 발견하신 이슈 해결하기

## ✅  To-do

- [ ] 게시글 POST 시 태그 값에 허용되지 않는 값을 넣을 때, 400 에러가 나옴 (날짜 에러)
- [ ] 게시글 검색... 게시글 생성하고나서 검색하면 내가 작성한 게 나오지 않아요~! (상세 검색은 됨)
- [ ] 게시글 POST 완료 시 반환 값은 id만 필요
