### ISSUE TITLE
[refactor] auth API 마무리

### ISSUE THREAD

**Issue by yaongmeow** [boostcampwm2023/iOS07-traveline#225]
## 📌  Issue

테스트를 거처 auth API 작업을 완료합니다.

## ✅  To-do

- [x] auth API에 수정이 필요한 부분 수정
- [x] 테스트를 위해 남겨둔 `console.log` 제거
- [x] 로컬 테스트 결과 확인
- [x] 배포 후 테스트 결과 확인
