### ISSUE TITLE
[feat] 검색 기능 서버 연결

### ISSUE THREAD

**Issue by kth1210** [boostcampwm2023/iOS07-traveline#261]
## 📌  Issue

- 홈 화면, 검색 결과 화면, 필터에 대해서 검색 기능을 서버와 연결합니다!

## ✅  To-do

- [x] 페이지네이션 적용
- [x] 홈 화면 리스트 연결
- [x] 검색 결과 화면 리스트 연결
- [x] 필터 적용 테스트
