### ISSUE TITLE
[fix] iOS 피드백 반영

### ISSUE THREAD

**Issue by kmi0817** [boostcampwm2023/iOS07-traveline#263]
## ✅  To-do

- [x]  `postings/`에서 좋아요 개수 반환: 좋아요 개수 나타내는 필드 추가
- [x] 타임라인 POST/PUT의 반환 결과 수정: { id: string }
- [x] 업로드하는 파일 크기 2MB로 제한
