### ISSUE TITLE
[feat] users API 구현

### ISSUE THREAD

**Issue by yaongmeow** [boostcampwm2023/iOS07-traveline#27]
## 📌  Issue

users API 를 구현합니다.
## ✅  To-do

- [ ] GET `:id` API
- [ ] PUT `:id` API
- [ ] GET `duplicate` API
