### ISSUE TITLE
[feat] 1차 QA 버그 수정

### ISSUE THREAD

**Issue by 0inn** [boostcampwm2023/iOS07-traveline#278]
## 📌  Issue

1차 QA 버그 수정합니다.

## ✅  To-do

- [x] 여행 생성 안되는 이슈 (서버 query와 이름 다른 이슈 해결)
- [x] multipart 옵셔녈 값 추출 안되는 이슈 해결
- [x] 프로필 이미지 업로드 안되는 이슈 해결
- [x] 여행 일정 n개월되면 앱 터지는 이슈 - 최대 한 달로 고정
- [x] 썸네일 이미지 없는 경우 뷰 분기
- [x] 프로필 이미지 radius 처리
