### ISSUE TITLE
[feat] 여행 관리 API 연결

### ISSUE THREAD

**Issue by 0inn** [boostcampwm2023/iOS07-traveline#279]
## 📌  Issue

여행 API 연결합니다.

## ✅  To-do

- [x] 여행 수정 API
- [x] 여행 삭제 API
- [x] 여행 신고 API
- [x] 여행 좋아요 API
