### ISSUE TITLE
[feat] 여행 생성 화면 구현

### ISSUE THREAD

**Issue by kth1210** [boostcampwm2023/iOS07-traveline#33]
## 📌  Issue

- 여행 생성 화면을 구현합니다.
- ViewModel과 더미를 통해 테스트해볼 예정입니다.

## ✅  To-do

- [ ] 여행 제목 TextField 구현
- [ ] 지역 선택 Button 구현
- [ ] 출발일, 도착일 Date Picker 연결
- [ ] 태그 CollectionView 구현
- [ ] ViewModel 테스트
