### ISSUE TITLE
[docs] BE 부분 작성

### ISSUE THREAD

**Issue by kmi0817** [boostcampwm2023/iOS07-traveline#359]
## ✅  To-do

- [ ] 프로젝트 구조 이미지 첨부
- [ ] BE 기술 스택 작성 (키워드만이라도)
- [ ] 우리의 도전들 링크 달기

**Comment by kmi0817** [comment]
iOS와 BE가 하나의 README를 계속 수정하려니 충돌이 발생하여,
BE가 README 내용을 iOS에 전달하면 iOS 측에서 한꺼번에 취합하여 main으로 merge하기로 했습니다~!

**Comment by kmi0817** [comment]
기술 스택 부분 추가하기 위해 다시 open 합니다,,^^ github에서 직접 수정하면 프리티어가 적용 안 돼서 괜찮을 것 같아용
