### ISSUE TITLE
[feat] 홈 리스트 UI 구현

### ISSUE THREAD

**Issue by 0inn** [boostcampwm2023/iOS07-traveline#38]
## 📌  Issue

홈 리스트 UI 구현합니다.
<img width="230" alt="image" src="https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/8785e8dd-016f-441e-b2d7-5d1dc9c0f59c">

## ✅  To-do

- [x] 홈 리스트 Cell 구현
- [x] 홈 리스트 UI 구현
- [x] Sample Model 추가 후 테스트
