### ISSUE TITLE
[fix] 타임라인 수정 / 삭제 간 문제 해결

### ISSUE THREAD

**Issue by kth1210** [boostcampwm2023/iOS07-traveline#383]
## 📌  Issue

- 타임라인 수정 / 삭제 연결 간 발생한 문제들을 해결합니다.

> 1. 수정 -> 취소 시 다시 수정이 안되는 현상
> 2. 지속적으로 수정 시 다운샘플링이 중복 적용 (기 공유된 사항)
> 2-1. 수정 화면 이동 시 기존 이미지가 노출되지 않는 문제
> 3. 수정 화면에서 이미지 갤러리에서 선택 시 간헐적으로 버튼에 이미지가 업데이트 되지 않는 현상
> 4. 수정 화면에서 기존 이미지가 있을 때 이미지 갤러리에서 선택 시 업데이트 안되거나, 글자 입력 시 기존 이미지로 바뀌는 현상
> 5. 이미지만 변경했을 시 완료 버튼 활성화 되지 않음
> 5-1. 해당 원인은 이미지 데이터를 가져오는 시점을 완료 버튼 눌렀을 때로 변경하게 되었는데 (TimelineDetailVC에서 받아온 이미지는 String이기 때문에) 이 때문이 아닌가 싶긴합니다.

## ✅  To-do

- [x] 수정 -> 취소 시 다시 수정이 안되는 현상 해결
- [x] 수정 화면 이동 시 기존 이미지가 노출되지 않는 문제 해결
- [x] 지속적으로 수정 시 다운샘플링이 중복 적용되는 문제 해결
- [x] 수정 화면의 이미지 갤러리에서 선택 시 간헐적으로 버튼에 이미지가 업데이트 되지 않는 문제 해결
- [x] 수정 화면에서 기존 이미지가 있을 때 이미지 갤러리에서 새로 선택 시 업데이트 안되는 문제 해결
- [x] 이미지 변경 후 글자 입력 시 기존 이미지로 바뀌는 현상 해결
- [x] 이미지만 변경했을 시 완료 버튼 활성화 되지 않는 현상 해결
