### ISSUE TITLE
[refactor] 애플 로그인 마이그레이션

### ISSUE THREAD

**Issue by yaongmeow** [boostcampwm2023/iOS07-traveline#389]
## 📌  Issue

기존 부캠 계정에서 팀원 개발자 계정으로 마이그레이션을 진행합니다.

## ✅  To-do

- [x] KEY ID 수정
- [x] TEAM ID 수정
- [x] CLIENT ID 수정
- [x] AUTH KEY 값 수정
