### ISSUE TITLE
[test] 배포용 서버 생성에 따른 깃허브 액션 수정

### ISSUE THREAD

**Issue by kmi0817** [boostcampwm2023/iOS07-traveline#404]
## ✅  To-do

- [ ] 기존 깃허브 액션 제목 변경: deploy.yml에서 deploy-test.yml으로
- [ ] 배포용 깃허브 액션 파일 생성 (제목 deploy.yml)
- [ ] 깃허브 시크릿에 등록된 환경 변수 추가, 수정, 삭제
