### ISSUE TITLE
[refactor] Storage Module 수정

### ISSUE THREAD

**Issue by yaongmeow** [boostcampwm2023/iOS07-traveline#51]
## 📌  Issue

Storage Module을 수정합니다.

## ✅  To-do

- [ ] 이미지 URL 받아오는 함수 추가
- [ ] 이미지 업로드 시 저장 경로를 지정할 수 있도록 수정
- [ ] 이미지 업로드 시 저장 경로를 받아올 수 있도록 수정
