### ISSUE TITLE
[refactor] Posting 모듈 리뷰 반영

### ISSUE THREAD

**Issue by kmi0817** [boostcampwm2023/iOS07-traveline#55]
## 📌  Issue

#42 [feat] 특정 게시글 CRUD 구현 PR에서 받은 리뷰 반영

## ✅  To-do

- [ ] Posting 수정/삭제 시 id에 해당하는 게시글이 없을 경우 예외 처리 추가
- [ ] posting 엔티티 파일에서 필드명 스네이크 케이스 → 카멜 케이스로 변경
    - [ ] GET `postings/:id`에서 스프레드 연산 활용

**Comment by kmi0817** [comment]
#85 에 통합되므로 해당 이슈를 close 하겠습니다~
