### ISSUE TITLE
[refactor] users API 리뷰 반영

### ISSUE THREAD

**Issue by yaongmeow** [boostcampwm2023/iOS07-traveline#59]
## 📌  Issue

#52 users API 구현 PR에서 받은 리뷰 반영

## ✅  To-do

- [ ] GET `/users/duplicate`를 GET `users/:id` 상단으로 옮기기
- [ ] 네이밍 통일 (복수형)
- [ ] 프로필 사진 업데이트 시 회원 존재 여부 확인
- [ ] exception throw 하는 부분 수정
