### ISSUE TITLE
[refactor] DB 구조 및 정책 수정

### ISSUE THREAD

**Issue by kmi0817** [boostcampwm2023/iOS07-traveline#85]
## 📌  Issue

- 지난 멘토링(11월 20일) 이후 백엔드 팀원과의 회의를 거쳐 수정된 DB 구조를 반영한다.
- 태그와 게시글을 relation으로 풀어낸다.

## ✅  To-do

- [x] 각 태그의 Entity 정의
- [x] 기존 Posting Entity 수정
    - #55 태스크 포함됨
- [x] 위 Entity를 기반으로 dto 수정
- [x] 위 Entity와 dto를 기반으로 Posting API 코드 수정
    - #53 태스크 포함됨
