### ISSUE TITLE
[refactor] 로그인 확장성을 위한 DB 구조 수정

### ISSUE THREAD

**Issue by yaongmeow** [boostcampwm2023/iOS07-traveline#86]
## 📌  Issue

로그인 확장성을 위해 `user` 테이블 구조를 변경합니다.

## ✅  To-do

- [x] 소셜 로그인 구분자 `resource_id` 컬럼 추가
- [x] 소셜 로그인 `type` 컬럼 추가
- [x] `social_login` 테이블 추가
