### ISSUE TITLE
[feat] 타임라인 - 여행 정보 UI 구현

### ISSUE THREAD

**Issue by kth1210** [boostcampwm2023/iOS07-traveline#87]
## 📌  Issue
- 타임라인 화면 중 여행 정보 UI를 먼저 구현합니다!
<img width="350" alt="스크린샷 2023-11-22 오후 12 13 58" src="https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/19d661cb-e533-47ba-935f-f9acc58d5d1b">

## ✅  To-do

- [x] 여행 정보 Cell 구현
- [x] 타임라인 ViewController 생성
- [x] CollectionView + Compositional Layout 적용
- [x] 여행 정보 Cell delegate 연결 (좋아요)
