### ISSUE TITLE
[feat] 타임라인 작성 뷰 UI

### ISSUE THREAD

**Issue by otoolz** [boostcampwm2023/iOS07-traveline#89]
## 📌  Issue

타임라인 작성 뷰 UI를 만들어요.

## ✅  To-do

- [x] 타임라인 작성 뷰 UI
- [x] 앨범 불러오기
- [x] 시간 선택 뷰 작성 및 연결
- [x] 장소 선택 뷰 작성 및 연결
